### ISSUE TITLE
Cozy for Pine64

### ISSUE THREAD

**Issue by ashwinjagadeesh-zz** [cozy/cozy-debian#49]
Is there an easy way to install cozy for Pine64? Dont think cozy supports arm 64 based debian installation as of now.

**Comment by jsilvestre** [comment]
Hello @ashwinjagadeesh,

I won't be able to tell you exactly why it's not possible, but we tried and CouchDB (I think it was CouchDB) could not be installed at all on Pine64. So as of today, it's not possible. Since I'm not 100% sure if myself, I'll ask a colleague to correct me if I'm wrong.

Cheers,
Joseph.

**Comment by jsilvestre** [comment]
Ok, my colleague @aeris tells me it's Node.js that can't be installed on Pine64! Since we are in the process of rewriting the backend in Go, we will tackle this problem again at some point. I can't give you any ETA for this, we hope that we'll be able to tackle this problem at the end of 2017, but we really don't know at this point.

**Comment by babolivier** [comment]
Hi @jsilvestre and @ashwinjagadeesh,

> Ok, my colleague @aeris tells me it's Node.js that can't be installed on Pine64!

That's not right, I have a Pine64 (currently laying in a bag) and remember using some Node.js apps on it 😄

Node.js's binaries for ARM64 can be downloaded on the [download page](https://nodejs.org/en/download/) under "ARMv8". Not sure it's correctly packaged for this architecture on Debian/Ubuntu, though.

However, I had troubles installing Cozy at the time because of leveldb (dependency of Cozy's indexer) not supporting ARM64. AFAIK, this issue has been fixed for several months now, but I don't know if all the packages in Cozy's dependencies tree supports this architecture (which is required for Cozy to run).

**Comment by clochix** [comment]
The Node.js version of Cozy is now deprecated.

To learn how to install the new version of Cozy, please refer to our (in progress) [documentation](https://docs.cozy.io/en/).
